import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./Navigation";
import Footer from "./Footer";

// Keep fonts normal, but apply variables in CSS for SSR consistency
export const metadata: Metadata = {
  title: "कचरा सेतु",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Only deterministic classNames here */}
      <body className="antialiased">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
